# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  schedule:
    - cron: "0 * * * 1-5"

jobs:
  build-run-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Build & Run
        run: |
          npm install -g yarn
          yarn
          yarn build
          yarn start

      - name: Commit files
        run: |
          git config --local user.email "wataru.oguchi.0to1@gmail.com"
          git config --local user.name "Wataru Bot"
          git status > last_updated
          date >> last_updated
          git add last_updated src/.encoded src/.json
          git commit -v -m "[Bot] GitHub Actions - auto run"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
